window.FITNESS_THUMBNAILS = {
  "FULL MIX 1|1": "miniatures/FM4/01_developpe_incline_halteres.jpg",
  "FULL MIX 1|2": "miniatures/FM1/02_ecarte_poulie_basse_vers_haut_debout.jpg",
  "FULL MIX 1|3": "miniatures/FM1/03_developpe_epaules_assis_halteres.jpg",
  "FULL MIX 1|4": "miniatures/FM1/04_elevations_laterales_halteres.jpg",
  "FULL MIX 1|5": "miniatures/FM1/05_rowing_barre_EZ.jpg",
  "FULL MIX 1|6": "miniatures/FM1/06_biceps_black_jack_poulie_basse_barre_droite.jpg",
  "FULL MIX 1|7": "miniatures/FM1/07_magic_triceps_barre_EZ.jpg",
  "FULL MIX 1|8": "miniatures/FM1/08_crunch_poulie_haute_a_genoux.jpg",
  "FULL MIX 1|9": "miniatures/FM1/09_releve_genoux_suspendu.jpg",
  "FULL MIX 1|10": "miniatures/FM1/10_wood_chop_poulie.jpg",
  "FULL MIX 2|1": "miniatures/FM2/01_rowing_poitrine_appuyee_banc_incline_halteres.jpg",
  "FULL MIX 2|2": "miniatures/FM2/02_tirage_vertical_prise_neutre.jpg",
  "FULL MIX 2|3": "miniatures/FM2/03_tractions.jpg",
  "FULL MIX 2|4": "miniatures/FM2/04_curl_biceps_pupitre_barre_EZ.jpg",
  "FULL MIX 2|5": "miniatures/FM2/05_spider_curl_halteres_banc_incline.jpg",
  "FULL MIX 2|6": "miniatures/FM2/06_extension_magic_triceps_halteres.jpg",
  "FULL MIX 2|7": "miniatures/FM2/07_extension_triceps_au_dessus_tete_corde.jpg",
  "FULL MIX 2|8": "miniatures/FM2/08_elevation_laterale_unilaterale_poulie_derriere_corps.jpg",
  "FULL MIX 2|9": "miniatures/FM2/09_pec_deck_butterfly.jpg",
  "FULL MIX 2|10": "miniatures/FM2/10_circuit_abdos_intensif_8_min.jpg",
  "FULL MIX 3|1": "miniatures/FM3/01_leg_press_horizontale.jpg",
  "FULL MIX 3|2": "miniatures/FM3/02_leg_curl_assis.jpg",
  "FULL MIX 3|3": "miniatures/FM3/03_fentes_bulgares_halteres.jpg",
  "FULL MIX 3|4": "miniatures/FM3/04_mollets_debout_smith_machine.jpg",
  "FULL MIX 3|5": "miniatures/FM3/05_leg_extension.jpg",
  "FULL MIX 3|6": "miniatures/FM3/06_developpe_militaire.jpg",
  "FULL MIX 3|7": "miniatures/FM3/07_elevation_laterale_unilaterale_poulie_basse_devant_corps.jpg",
  "FULL MIX 3|8": "miniatures/FM3/08_extension_lombaire_banc_poids_poitrine.jpg",
  "FULL MIX 3|9": "miniatures/FM3/09_extension_triceps_unilaterale_poulie.jpg",
  "FULL MIX 3|10": "miniatures/FM3/10_pallof_press.jpg",
  "FULL MIX 4|1": "miniatures/FM4/01_developpe_incline_halteres.jpg",
  "FULL MIX 4|2": "miniatures/FM4/02_ecarte_incline_poulie_basse.jpg",
  "FULL MIX 4|3": "miniatures/FM4/03_elevation_laterale_unilaterale_poulie_derriere_corps.jpg",
  "FULL MIX 4|4": "miniatures/FM4/04_oiseau_halteres_poitrine_appuyee_banc_incline.jpg",
  "FULL MIX 4|5": "miniatures/FM4/05_curl_biceps_poulie_basse_V.jpg",
  "FULL MIX 4|6": "miniatures/FM4/06_extension_triceps_corde.jpg",
  "FULL MIX 4|7": "miniatures/FM4/07_tirage_vertical_prise_neutre.jpg",
  "FULL MIX 4|8": "miniatures/FM4/08_adduction_hanche_machine.jpg",
  "FULL MIX 4|9": "miniatures/FM4/09_abduction_hanche_machine.jpg",
  "FULL MIX 4|10": "miniatures/FM4/10_face_pull_corde_poulie_haute.jpg",
  "G1A|1": "miniatures/G1A/01_developpe_couche_machine_convergente.jpg",
  "G1A|2": "miniatures/G1A/02_ecarte_unilateral_poulie_basse.jpg",
  "G1A|3": "miniatures/G1A/03_pec_deck_butterfly.jpg",
  "G1A|4": "miniatures/G1A/04_dips_lestes.jpg",
  "G1A|5": "miniatures/G1A/05_curl_biceps_barre_EZ_debout_v24251.png",
  "G1A|6": "miniatures/G1A/06_curl_biceps_halteres.jpg",
  "G1A|7": "miniatures/G1A/07_curl_unilateral_pupitre_vertical.jpg",
  "G1A|8": "miniatures/G1A/08_crunch_abdominal.jpg",
  "G1A|9": "miniatures/G1A/09_abdominaux.jpg",
  "G1B|1": "miniatures/G1B/01_ecarte_a_la_poulie_basse_assis_sur_banc.jpg",
  "G1B|2": "miniatures/G1B/02_developpe_couche_avec_halteres.jpg",
  "G1B|3": "miniatures/G1B/03_ecarte_couche_avec_halteres.jpg",
  "G1B|4": "miniatures/G1B/04_pec_deck_butterfly.jpg",
  "G1B|5": "miniatures/G1B/05_spider_curl_barre_EZ.jpg",
  "G1B|6": "miniatures/G1B/06_curl_marteau_avec_halteres.jpg",
  "G1B|7": "miniatures/G1B/07_curl_biceps_poulie_basse_V.jpg",
  "G1B|8": "miniatures/G1B/08_circuit_abdos_8min.jpg",
  "G1C|1": "miniatures/G1C/01_developpe_incline_halteres.jpg",
  "G1C|2": "miniatures/G1C/02_ecarte_incline_halteres.jpg",
  "G1C|3": "miniatures/G1C/03_ecarte_unilateral_poulie_basse.jpg",
  "G1C|4": "miniatures/G1C/04_chest_press.jpg",
  "G1C|5": "miniatures/G1C/05_curl_incline_halteres.jpg",
  "G1C|6": "miniatures/G1C/06_curl_biceps_barre_EZ_prise_pronation.jpg",
  "G1C|7": "miniatures/G1C/07_curl_biceps_machine.jpg",
  "G1C|8": "miniatures/G1C/08_gainage.jpg",
  "G2A|1": "miniatures/G2A/01_tirage_horizontal_poulie_double_poignee.jpg",
  "G2A|2": "miniatures/G2A/02_tirage_bras_tendus_poulie_haute_barre.jpg",
  "G2A|3": "miniatures/G2A/03_rowing_unilateral_haltere.jpg",
  "G2A|4": "miniatures/G2A/04_tirage_vertical_prise_serree_V_v24187.jpg",
  "G2A|5": "miniatures/G2A/05_extension_triceps_corde.jpg",
  "G2A|6": "miniatures/G2A/06_barre_au_front_front_extension.jpg",
  "G2A|7": "miniatures/G2A/07_dips_sur_banc.jpg",
  "G2A|8": "miniatures/G2A/08_releve_de_jambes.jpg",
  "G2A|9": "miniatures/G2A/09_flexions_laterales_du_buste.jpg",
  "G2B|1": "miniatures/G2B/01_tirage_vertical_prise_neutre_barre.jpg",
  "G2B|2": "miniatures/G2B/02_tirage_horizontal_prise_large.jpg",
  "G2B|3": "miniatures/G2B/03_rowing_assis_machine_seated_row.jpg",
  "G2B|4": "miniatures/G2B/04_tirage_vertical_prise_serree_V.jpg",
  "G2B|5": "miniatures/G2B/05_extension_triceps_corde.jpg",
  "G2B|6": "miniatures/G2B/06_extension_triceps_au_dessus_tete_haltere.jpg",
  "G2B|7": "miniatures/G2B/07_extension_triceps_couche_halteres.jpg",
  "G2B|8": "miniatures/G2B/08_crunch_leste_banc_decline_10kg.jpg",
  "G2B|9": "miniatures/G2B/09_flexion_laterale_lestee_banc_decline_kettlebell.jpg",
  "G2C|1": "miniatures/G2C/01_souleve_de_terre_barre.jpg",
  "G2C|2": "miniatures/G2C/02_rowing_barre.jpg",
  "G2C|3": "miniatures/G2C/03_lat_pulldown.jpg",
  "G2C|4": "miniatures/G2C/04_rowing_poulie_basse_prise_large_haut_torse.jpg",
  "G2C|5": "miniatures/G2C/05_extension_triceps_poulie_arriere.jpg",
  "G2C|6": "miniatures/G2C/06_extension_triceps_poulie_haute_prise_inversee.jpg",
  "G2C|7": "miniatures/G2C/07_dips_assis_machine.jpg",
  "G2C|8": "miniatures/G2C/08_circuit_abdos_8_min.jpg",
  "G3A|1": "miniatures/G3A/01_developpe_epaules_assis_halteres.jpg",
  "G3A|2": "miniatures/G3A/02_tirage_menton_barre_EZ.jpg",
  "G3A|3": "miniatures/G3A/03_elevation_laterale_unilaterale_poulie_basse.jpg",
  "G3A|4": "miniatures/G3A/04_elevations_laterales_halteres.jpg",
  "G3A|5": "miniatures/G3A/05_hack_squat.jpg",
  "G3A|6": "miniatures/G3A/06_leg_extension.jpg",
  "G3A|7": "miniatures/G3A/07_leg_curl_allonge.jpg",
  "G3A|8": "miniatures/G3A/08_mollets_debout_machine.jpg",
  "G3A|9": "miniatures/G3A/09_circuit_abdos_complet_8min.jpg",
  "G3B|1": "miniatures/G3B/01_developpe_militaire_barre.jpg",
  "G3B|2": "miniatures/G3B/02_oiseau_machine_reverse_pec_deck.jpg",
  "G3B|3": "miniatures/G3B/03_elevations_frontales_sur_banc.jpg",
  "G3B|4": "miniatures/G3B/04_squat_libre.jpg",
  "G3B|5": "miniatures/G3B/05_leg_press.jpg",
  "G3B|6": "miniatures/G3B/06_mollets_assis_machine.jpg",
  "G3B|7": "miniatures/G3B/07_releve_de_jambes.jpg",
  "G3B|8": "miniatures/G3B/08_exercice_8.jpg",
  "G3B|9": "miniatures/G3B/09_exercice_9.jpg",
  "G3C|1": "miniatures/G3C/01_developpe_militaire_debout_barre.jpg",
  "G3C|2": "miniatures/G3C/02_oiseau_poulie.jpg",
  "G3C|3": "miniatures/G3C/03_elevation_Y_poulie_basse.jpg",
  "G3C|4": "miniatures/G3C/04_elevation_laterale_couchee_banc_incline_haltere.jpg",
  "G3C|5": "miniatures/G3C/05_goblet_squat.jpg",
  "G3C|6": "miniatures/G3C/06_fentes_marchees.jpg",
  "G3C|7": "miniatures/G3C/07_mollets_assis_machine.jpg",
  "G3C|8": "miniatures/G3C/08_chaise_romaine.jpg",
  "G3C|9": "miniatures/G3C/09_flexion_laterale_lestee_banc_decline_kettlebell.jpg"
};
